spring.application.name=kargo_takip
springdoc.swagger-ui.path=/swagger-ui.html
spring.datasource.url=jdbc:postgresql://localhost:5432/kargo_takip
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
